import { BasketConstTypes } from '@shared/types/BasketConsts'

export enum ValidationErrorCode {
  AIRTIME_DEVICE_MISMATCH = 'AIRTIME_DEVICE_MISMATCH',
  BASKET_AIRTIME_PLAN = 'basket_airtime_plan',
  BASKET_AIRTIME_PLAN_LENGTH = 'basket_airtime_plan_length',
  BSKT_INVALID_INPUT_042 = 'BSKT_INVALID_INPUT_042',
  BSKT_INVALID_INPUT_047 = 'BSKT_INVALID_INPUT_047',
  BSKT_INVALID_INPUT_037 = 'BSKT_INVALID_INPUT_037',
  BASKET_LOAN_CAP = 'BASKET_LOAN_CAP',
  BASKET_PHONE_CAP = 'BASKET_PHONE_CAP',

  BASKET_WATCH_CAP = 'BASKET_WATCH_CAP',
  LOAN_DECLINE_CHECKOUT_HANDSET_ONLY = 'LOAN_DECLINE_CHECKOUT_HANDSET_ONLY',
  LOAN_DECLINE_CHECKOUT_HANDSET_WATCH = 'LOAN_DECLINE_CHECKOUT_HANDSET_WATCH',
  LOAN_DECLINE_CHECKOUT_WATCH_HANDSET = 'LOAN_DECLINE_CHECKOUT_WATCH_HANDSET',
  LOAN_DECLINE_CHECKOUT_WATCH_ONLY = 'LOAN_DECLINE_CHECKOUT_WATCH_ONLY',
  LOAN_INVALID_UPFRONT_COST = 'LOAN_INVALID_UPFRONT_COST',
  LOAN_INVALID_DURATION = 'LOAN_INVALID_DURATION',
  MAX_SB_PLANS_EXCEEDED = 'MAX_SB_PLANS_EXCEEDED',

  MAXIMUM_ALLOWED_LOANS = 'MAXIMUM_ALLOWED_LOANS',
  MAXIMUM_LOANS_FOR_CTN = 'MAXIMUM_LOANS_FOR_CTN',
  MAX_LOAN_LIMIT_REACHED = 'MAX_LOAN_LIMIT_REACHED',

  MAXIMUM_CTNS_WITH_CONCURRENT_LOANS = 'MAXIMUM_CTNS_WITH_CONCURRENT_LOANS',
  MAXIMUM_LENDING_LIMIT = 'MAXIMUM_LENDING_LIMIT',

  REPAYMENT_ISSUES = 'REPAYMENT_ISSUES',
  SUBCATEGORY_LOAN_NONLOAN_MIX_HANDSET = 'SUBCATEGORY_LOAN_NONLOAN_MIX_HANDSET',
  SUBCATEGORY_LOAN_NON_LOAN_MIX_WATCH = 'SUBCATEGORY_LOAN_NON_LOAN_MIX_WATCH',
  SUBCATEGORY_SOLETRADER_INELIGIBLE_LOAN_PHONE = 'SUBCATEGORY_SOLETRADER_INELIGIBLE_LOAN_PHONE',
  SUBCATEGORY_SOLETRADER_INELIGIBLE_LOAN_WATCH = 'SUBCATEGORY_SOLETRADER_INELIGIBLE_LOAN_WATCH',
  SUBCATEGORY_SMALLBUSINESS_INELIGIBLE_HANDSET = 'SUBCATEGORY_SMALLBUSINESS_INELIGIBLE_HANDSET',
  TRADEIN_QUOTE_EXP = 'TRADEIN_QUOTE_EXP',
}

export const NOTIFICATIONS = {
  title: 'Uh-oh, something went wrong.',
  message: 'Something went wrong. Please try again, or contact customer support.',
  ctaText: '',
  ctaUrl: '',
  type: 'error',
}

export enum BenefitId {
  DEVICE_CARE = '030010',
  SMARTWATCH_CONNECTIVITY = '030030',
  SMARTWATCH_CONNECTIVITY_BUSINESS = '030030_Business',
  DATA_BOOSTER_X3 = '030040',
  DATA_BOOSTER_X6 = '030050',
}

export const DiscountId = {
  SMARTWATCH_CONNECTIVITY: '113119',
}

export const DiscountType = {
  MULTI_PACKAGE_DISCOUNT: 'multi_package_discount',
  ACCESSORY_DISCOUNT: 'accessory_discount',
}

export const BASKET_CONSTS: BasketConstTypes = {
  SIM_TYPE_ESIMONLY: 'ESIMONLY',
  SIM_TYPE_HYBRID: 'HYBRID',
  SIM_TYPE_PHYSICAL: 'PHYSICAL',

  PRODUCT_SUB_CLASS_WATCH: 'WATCH',
  PRODUCT_SUB_CLASS_HANDSET: 'HANDSET',
  PRODUCT_SUB_CLASS_CORE: 'CORE',

  PRODUCT_CLASS_HANDSET: 'HANDSET',
  PRODUCT_CLASS_EHANDSET: 'EHANDSET',
  PRODUCT_CLASS_SIM_CARD: 'SIM CARD',
  PRODUCT_CLASS_DATA_DEVICE: 'DATA_DEVICE',
  PRODUCT_CLASS_ACCESSORY: 'ACCESSORIES',
  PRODUCT_CLASS_DISCOUNT: 'DISCOUNT',

  SERVICE_PRODUCT_CLASS_INSURANCE: 'INSURANCE',
  SERVICE_PRODUCT_CLASS_SUPER_WIFI: 'Super Wi-Fi',
  SERVICE_PRODUCT_CLASS_BONUS_DATA: 'Bonus Data Bundle',
  SERVICE_PRODUCT_CLASS_FIXED_LINE: 'Fixed Line',
  SERVICE_PRODUCT_CLASS_FIXED_BROADBAND_SERVICE: 'Fixed Broadband Service',
  SERVICE_PRODUCT_CLASS_HYBRID_BUNDLES: 'Hybrid Bundles',

  PLAN_TYPE_SIMO: 'SIMO',
  PLAN_TYPE_WATCH_SIMO: 'WATCH_SIMO',
  PLAN_TYPE_DATA_SIMO: 'DATA_SIMO',
  PLAN_TYPE_BINGO: 'BINGO',
  PLAN_TYPE_HANDSET: 'HANDSET',
  PLAN_TYPE_BROADBAND_FTTH: 'BROADBAND:FTTH',
  PLAN_TYPE_BROADBAND_FTTP: 'BROADBAND:FTTP',
  PLAN_TYPE_BROADBAND_FTTC: 'BROADBAND:FTTC',
  PLAN_TYPE_DATA_DEVICE: 'DATA_DEVICE',
  PLAN_TYPE_ACCESSORY: 'ACCESSORIES',
  PLAN_TYPE_RED_HYBRID: 'RED_HYBRID_ONLINE',

  MP_TYPE_LIMITED_TIME: 'limited_time',

  BUNDLE_DISPLAY_NAME_ESIM: 'ESIM',
  BUNDLE_TYPE_BASIC: 'BASIC',
  BUNDLE_TYPE_BASICS_PLAN: 'BASICS PLAN',
  BUNDLE_PAYMENT_TYPE_PRE: 'PREPAID',
  BUNDLE_CLASS_DATA_DEVICE: 'DATA_DEVICE',
  BUNDLE_CLASS_DATA_SIMO: 'DATA_SIMO',
  BUNDLE_CLASS_SIMO: 'SIMO',
  BUNDLE_CLASS_WATCH_SIMO: 'WATCH_SIMO',

  ACCOUNT_CATEGORY_BUSINESS: 'BUSINESS',
  ACCOUNT_CATEGORY_CONSUMER: 'CONSUMER',

  ACCOUNT_TYPE_SMALLBUSINESS: 'SMALL-BUSINESS',

  MAKE_VODAFONE: 'VODAFONE',

  PAYMENT_POSTPAID: 'POSTPAID',
  UPGRADE_ORDER: 'UPGRADE',
}

// Match env variable strings
export const FEATURE_FLAGS_CONSTS = {
  BINGO: 'bingo',
  ESIM: 'esim',
  BINGO_LAUNCHED: 'bingo_launched',
  BINGO_ONENUMBERRENAME: 'bingo_onenumberrename',
}

export const FEATURE_FLAG_LD_KEYS: Record<string, string> = {
  [FEATURE_FLAGS_CONSTS.BINGO]: 'web-shop-basket-bingo-enabled',
  [FEATURE_FLAGS_CONSTS.ESIM]: 'web-shop-basket-esim-enabled',
  [FEATURE_FLAGS_CONSTS.BINGO_LAUNCHED]: 'web-shop-basket-bingo-launch-enabled',
  [FEATURE_FLAGS_CONSTS.BINGO_ONENUMBERRENAME]: 'web-shop-basket-bingo-onenumberrename-enabled',
}

export const URL_CONSTS = {
  SIM_SWAP: 'https://support.vodafone.co.uk/Mobile-plans-Pay-as-you-go-SIM/SIM-card/',
}

export const TACTICAL_TRADEIN_TEXT =
  'Trade-in saving is applied to Airtime Plan first. If additional discounts reduce your Airtime bill to less than £0pm, your balance will remain at £0pm and additional credits will not be applied.'
